
TITLE = "GREEN SQUARE"
SCALE = .8
RES = WIDTH, HEIGHT = 1600 * SCALE, 900 * SCALE
FPS = 60
PLAYER_X_SPEED = 10
PLAYER_Y_SPEED = 10 
FULL_SCREEN = False

SHOW_MENU = True
CAMERA_TARGET = None
CAMERA_MS = 1
